apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: banking
spec:
  replicas: 3
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bankingprod7frcnkacr.azurecr.io/banking-frontend:9570606
          ports:
            - containerPort: 80
              name: http

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

  strategy:
    canary:
      progressDeadlineAbort: true
      stableService: frontend-stable
      canaryService: frontend-canary

      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoutes:
              - name: frontend-route

      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - setWeight: 25
        - pause:
            duration: 2m
        - setWeight: 50
        - pause:
            duration: 5m
        - setWeight: 75
        - pause:
            duration: 2m
        - setWeight: 100