name: 'Terraform Steps'
description: 'Run Terraform plan, apply, destroy, linting, and security scans for specific environments'

inputs:
  client-id:
    description: 'Service principal Client ID'
    required: true
  client-secret:
    description: 'Service principal Client Secret'
    required: true
  default-subscription-id:
    description: 'Azure Subscription ID'
    required: true
  tenant-id:
    description: 'Azure Tenant ID'
    required: true
  environment:
    description: 'Target environment (dev, staging, prod)'
    required: true
    default: dev
  working-directory:
    description: 'Directory where Terraform configuration is located'
    required: false
    default: .
  plan-title:
    description: 'Title for Terraform plan comment'
    required: true
  terraform-version:
    description: 'Terraform version to use or "latest" for auto-detect'
    required: false
    default: '1.1.9'
  GITHUB_TOKEN:
    description: 'GitHub token for commenting on PRs'
    required: true
  destroy:
    description: 'Trigger terraform destroy'
    required: false
    default: false

branding:
  icon: 'coffee'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      id: setup_tf
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: ./infra/${{ inputs.environment }}

    - name: TFLint
      id: tflint
      run: tflint
      working-directory: ./infra/${{ inputs.environment }}

    - name: Checkov
      id: checkov
      run: checkov -d ./infra/${{ inputs.environment }}

    - name: TFSEC
      id: tfsec
      run: tfsec ./infra/${{ inputs.environment }}

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.default-subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
      working-directory: ./infra/${{ inputs.environment }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./infra/${{ inputs.environment }}

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out=tf.plan
        # Check if plan has changes
        terraform show -json tf.plan > plan.json
        jq -e '.resource_changes | length > 0' plan.json > /dev/null
      env:
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.default-subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
      working-directory: ./infra/${{ inputs.environment }}

    - name: Terraform Show
      id: show
      run: terraform show -no-color tf.plan > /tmp/plan.txt
      env:
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.default-subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
      working-directory: ./infra/${{ inputs.environment }}

    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          const fs = require("fs");
          const plan = fs.readFileSync("/tmp/plan.txt", "utf8");
          const maxGitHubBodyCharacters = 65536;
          function chunkSubstr(str, size) {
            const numChunks = Math.ceil(str.length / size);
            const chunks = new Array(numChunks);
            for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
              chunks[i] = str.substr(o, size);
            }
            return chunks;
          }
          var plans = chunkSubstr(plan, maxGitHubBodyCharacters);
          for (let i = 0; i < plans.length; i++) {
            const output = `### ${{ inputs.plan-title }} Part # ${i + 1}
#### Terraform Format ðŸ–Œ \`${{ steps.fmt.outcome }}\`
#### Terraform Init âš™ï¸ \`${{ steps.init.outcome }}\`
#### Terraform Plan ðŸ“– \`${{ steps.plan.outcome }}\`

<details><summary>Show Plan</summary>

\`\`\`
${plans[i]}
\`\`\`

</details>

*Pusher: @${{ github.actor }}, Workflow: \`${{ github.workflow }}\`, Environment: \`${{ inputs.environment }}\`*`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

    - name: Terraform Apply (fail-safe)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ -s plan.json ]; then
          terraform apply -input=false tf.plan
        else
          echo "No changes detected. Skipping apply."
        fi
      env:
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.default-subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
      working-directory: ./infra/${{ inputs.environment }}

    - name: Terraform Destroy
      if: ${{ inputs.destroy == 'true' }}
      run: terraform destroy -auto-approve
      env:
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.default-subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
      working-directory: ./infra/${{ inputs.environment }}
